# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('cost', models.IntegerField()),
                ('image', models.CharField(max_length=128)),
                ('image2', models.CharField(max_length=128)),
                ('intro', models.TextField()),
                ('ingredient', models.TextField()),
                ('manual', models.TextField()),
                ('enable', models.BooleanField(default=True)),
                ('sp', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=True)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('Image', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Type'),
        ),
    ]
