# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_category_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='enable',
            new_name='isActive',
        ),
    ]
