# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20160112_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='intro',
            new_name='explanation',
        ),
        migrations.AddField(
            model_name='item',
            name='introduction',
            field=models.TextField(default='Nano'),
            preserve_default=False,
        ),
    ]
