# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20160117_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='introduction',
            new_name='intro',
        ),
    ]
