# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20160117_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='explanation',
        ),
        migrations.AddField(
            model_name='item',
            name='Introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredient',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='manual',
            field=models.TextField(blank=True),
        ),
    ]
