# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20160120_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inventory',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
