# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20160130_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
