# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20160205_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
