# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('c1', models.CharField(blank=True, max_length=128)),
                ('c2', models.CharField(blank=True, max_length=128)),
                ('c3', models.CharField(blank=True, max_length=128)),
                ('c4', models.CharField(blank=True, max_length=128)),
                ('c5', models.CharField(blank=True, max_length=128)),
                ('c6', models.CharField(blank=True, max_length=128)),
                ('c7', models.CharField(blank=True, max_length=128)),
                ('c8', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
