# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
