# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_setting_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='is_active',
            new_name='isActive',
        ),
    ]
