# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160112_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
