# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 21:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160202_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 1, 21, 11, 18, 529615, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
