# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160211_2223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Notice',
        ),
    ]
