# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128)),
                ('totalAmount', models.IntegerField(default=0)),
                ('paymentMethod', models.IntegerField(default=0)),
                ('paymentStatus', models.IntegerField(default=0)),
                ('payerName', models.CharField(blank=True, max_length=128)),
                ('payerAddress', models.CharField(blank=True, max_length=128)),
                ('payerPhone', models.CharField(blank=True, max_length=128)),
                ('recipientName', models.CharField(blank=True, max_length=128)),
                ('recipientAddress', models.CharField(blank=True, max_length=128)),
                ('recipientPhone', models.CharField(blank=True, max_length=128)),
                ('status', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('num', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmae', models.CharField(max_length=128)),
                ('cost', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.GroupOrder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('fullName', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('ip', models.CharField(blank=True, max_length=15)),
                ('isVerified', models.BooleanField(default=False)),
                ('regDate', models.DateTimeField(auto_now_add=True)),
                ('changeDate', models.DateTimeField(auto_now=True)),
                ('resetCode', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
