# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0009_item_inventory'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAmount', models.IntegerField()),
                ('paymentMethod', models.IntegerField()),
                ('paymentStatus', models.IntegerField()),
                ('payerName', models.CharField(max_length=128)),
                ('payerAddress', models.CharField(max_length=128)),
                ('payerPhone', models.CharField(max_length=128)),
                ('recipientName', models.CharField(max_length=128)),
                ('recipientAddress', models.CharField(max_length=128)),
                ('recipientPhone', models.CharField(max_length=128)),
                ('recipientStatus', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField()),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.CharField(max_length=128)),
                ('itemNmae', models.CharField(max_length=128)),
                ('itemPrice', models.CharField(max_length=128)),
                ('itemQty', models.IntegerField()),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.GroupOrder')),
            ],
        ),
    ]
