# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 02:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_mycart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycart',
            old_name='Qty',
            new_name='qty',
        ),
        migrations.AddField(
            model_name='mycart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 30, 2, 15, 52, 909178, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
