# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20160130_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='date2',
            field=models.DateField(default=datetime.datetime(2016, 1, 30, 13, 15, 32, 149263, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
