# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_mycart_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='date2',
        ),
    ]
