# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20160130_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouporder',
            name='payerAddress',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='grouporder',
            name='payerName',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='grouporder',
            name='payerPhone',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='grouporder',
            name='recipientAddress',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='grouporder',
            name='recipientName',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='grouporder',
            name='recipientPhone',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='grouporder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
