# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 05:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20160131_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouporder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 31, 5, 27, 16, 432686, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
