# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_grouporder_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='itemQty',
            new_name='qty',
        ),
    ]
