# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 09:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20160131_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_verified',
            new_name='isVerified',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='changeDate',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 31, 9, 31, 38, 689453, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='regDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 31, 9, 31, 45, 391039, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
