# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20160201_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouporder',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
