# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_grouporder_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouporder',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mycart',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
