# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20160203_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='changeDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='regDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
