# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_grouporder_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouporder',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
