# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20160204_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouporder',
            old_name='recipientStatus',
            new_name='status',
        ),
    ]
