# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20160204_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='itemNmae',
            new_name='nmae',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='itemPrice',
            new_name='price',
        ),
    ]
