# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20160204_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycart',
            old_name='itemID',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='itemID',
            new_name='item',
        ),
    ]
