# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouporder',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
