# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=10)),
                ('Message', models.CharField(max_length=50)),
                ('MerchantID', models.CharField(max_length=15)),
                ('Amt', models.IntegerField()),
                ('TradeNo', models.CharField(max_length=20)),
                ('MerchantOrderNo', models.CharField(max_length=20)),
                ('PaymentType', models.CharField(max_length=10)),
                ('CheckCode', models.CharField(max_length=128)),
                ('ExpireDate', models.CharField(max_length=128)),
                ('BankCode', models.CharField(blank=True, max_length=128)),
                ('CodeNo', models.CharField(blank=True, max_length=128)),
                ('Barcode_1', models.CharField(blank=True, max_length=128)),
                ('Barcode_2', models.CharField(blank=True, max_length=128)),
                ('Barcode_3', models.CharField(blank=True, max_length=128)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.GroupOrder')),
            ],
        ),
        migrations.CreateModel(
            name='NotifyDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=10)),
                ('Message', models.CharField(max_length=50)),
                ('MerchantID', models.CharField(max_length=15)),
                ('Amt', models.IntegerField()),
                ('TradeNo', models.CharField(max_length=20)),
                ('MerchantOrderNo', models.CharField(max_length=20)),
                ('PaymentType', models.CharField(max_length=10)),
                ('RespondType', models.CharField(max_length=10)),
                ('CheckCode', models.CharField(max_length=128)),
                ('PayTime', models.CharField(max_length=128)),
                ('IP', models.CharField(max_length=15)),
                ('EscrowBank', models.CharField(blank=True, max_length=10)),
                ('TokenUseStatus', models.CharField(blank=True, max_length=1)),
                ('RespondCode', models.CharField(blank=True, max_length=5)),
                ('Auth', models.CharField(blank=True, max_length=6)),
                ('Card6No', models.CharField(blank=True, max_length=6)),
                ('Card4No', models.CharField(blank=True, max_length=4)),
                ('Inst', models.CharField(blank=True, max_length=10)),
                ('InstFirst', models.CharField(blank=True, max_length=10)),
                ('InstEach', models.CharField(blank=True, max_length=10)),
                ('ECI', models.CharField(blank=True, max_length=2)),
                ('PayBankCode', models.CharField(blank=True, max_length=10)),
                ('PayerAccount5Code', models.CharField(blank=True, max_length=5)),
                ('CodeNo', models.CharField(blank=True, max_length=30)),
                ('Barcode_1', models.CharField(blank=True, max_length=20)),
                ('Barcode_2', models.CharField(blank=True, max_length=20)),
                ('Barcode_3', models.CharField(blank=True, max_length=20)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.GroupOrder')),
            ],
        ),
    ]
