# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay2go', '0003_auto_20160203_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyurldb',
            name='Inst',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='notifyurldb',
            name='InstEach',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='notifyurldb',
            name='InstFirst',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
