# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay2go', '0004_auto_20160203_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyurldb',
            name='Amt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notifyurldb',
            name='CheckCode',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='notifyurldb',
            name='IP',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='notifyurldb',
            name='MerchantID',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='notifyurldb',
            name='MerchantOrderNo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='notifyurldb',
            name='Message',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notifyurldb',
            name='PayTime',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='notifyurldb',
            name='PaymentType',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='notifyurldb',
            name='RespondType',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='notifyurldb',
            name='Status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='notifyurldb',
            name='TokenUseStatus',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='notifyurldb',
            name='TradeNo',
            field=models.CharField(max_length=20),
        ),
    ]
