# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20160204_0328'),
        ('pay2go', '0005_auto_20160203_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerurldb',
            name='group',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.GroupOrder'),
            preserve_default=False,
        ),
    ]
